global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'momentum-x'
    static_configs:
      - targets: ['host.docker.internal:9090']
        labels:
          app: 'momentum-x'
          env: 'paper'
